#!/bin/bash

# Takes an isosec and returns entries which link to the given isosec.

set -e

if [[ -z "$ZETDIR" ]]; then
	>&2 echo "ZETDIR not set or is empty. Please set it to a valid location"
	exit 1
fi

if [[ (( ! -d "$ZETDIR" )) && (( -w "$ZETDIR" )) && (( -x "$ZETDIR" )) ]]; then
	>&2 echo "Err: Zet directory doesn't exist. Please create one and assign to env ZETDIR"
	exit 1
fi

GREP="grep"
if [[ -n $(which rg) ]]; then
	GREP="rg"
fi

cd "$ZETDIR" > /dev/null

ISOSEC="$1"

if [[ "$2" == "-v" ]]; then
	# If triggered from vim - vim will pass -v flag
	ISOSEC="${ISOSEC##*/}"
	ISOSEC="${ISOSEC::14}"
fi

set +e
zetloc "$ISOSEC" > /dev/null

if [[ $? == 1 ]]; then
	>&2 echo "Error locating '$ISOSEC'"
	exit 1
fi
set -e

ISOSEC=$($GREP -l "$ISOSEC" | while read -r line; do test=${line%/*}; echo -n "${test##*/} "; head -1 "$line"; done)

echo "${ISOSEC}"

